# Reads ../output/*.json (Java-generated) and writes src/data/experimentResults.js
import json, os
H = os.path.dirname(os.path.abspath(__file__)); O = os.path.join(H, '..', '..', 'output')
load = lambda f: json.load(open(os.path.join(O, f), encoding='utf-8'))
names = {'ring': 'propagation_report_ring_lattice__k_4_.json', 'random': 'propagation_report_erd_s_r_nyi_random.json',
         'scale': 'propagation_report_barab_si_albert_scale_free.json'}
prop = {}
for k, f in names.items():
    d = load(f); c = d['propagationCurve']
    prop[k] = dict(n=d['numNodes'], edges=d['numEdges'], gini=round(d['giniCoefficient'], 3), diameter=d['diameter'],
        apl=round(d['averagePathLength'], 2), t50=d['timeTo50PercentMs'], t90=d['timeTo90PercentMs'], t100=d['timeTo100PercentMs'],
        lastDeliveryMs=c[-1][0], reachedPct=d['percentNodesOnCanonicalChain'],
        curve=[[p[0], round(p[1], 1)] for i, p in enumerate(c) if i % 4 == 0 or i == len(c) - 1])
p = load('fault_tolerance_partition_report.json')
part = {k: p[k] for k in ['numNodes', 'percentNodesOnCanonicalChain', 'partitionReconvergenceTimeMs', 'totalBlocksMined', 'orphanBlocksCount', 'orphanBlockRate']}
out = '// GENERATED by scripts/build-data.py from ../output/*.json (Java-generated). Do not edit by hand.\n'
out += 'export const propagation = ' + json.dumps(prop) + ';\nexport const partition = ' + json.dumps(part) + ';\n'
out += '''// The tables below are retained in the root README and PNG charts because the Java experiments do not emit dedicated JSON for them.
export const crashSweep = [ // Root README reference table; T90 cross-checked against output/fault_tolerance_study.png
  {rate:0,online:100,t50:268,t90:374,agree:100},{rate:10,online:90,t50:268,t90:383,agree:98.9},
  {rate:20,online:80,t50:259,t90:394,agree:97.5},{rate:30,online:70,t50:251,t90:354,agree:98.6},
  {rate:40,online:60,t50:232,t90:375,agree:96.7},{rate:50,online:50,t50:216,t90:445,agree:90.0}];
export const giniSizes = [20,50,100,200,300,400,500];
export const giniByN = { // Root README reference table; matches output/decentralization_gini_vs_n.png
  ring:[0,0,0,0,0,0,0], random:[0.3079,0.2712,0.1718,0.1286,0.1092,0.0986,0.0855], scale:[0.2944,0.3350,0.3557,0.3609,0.3641,0.3721,0.3648]};
'''
open(os.path.join(H, '..', 'src', 'data', 'experimentResults.js'), 'w', encoding='utf-8').write(out)
print(len(out), 'bytes', {k: (v['reachedPct'], v['t100'], v['lastDeliveryMs']) for k, v in prop.items()}, part)
